name: CI

on:
  push:
    branches:
      - python3-ci
      - python3
      - master
  pull_request:
    branches:
      - python3-ci
      - python3
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Check for script working
        run: echo Hello, world!
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: praveenpkg8/GitDemo1
          path: GitDemo1
      - name: Testing file
        run: ls GitDemo1
      - name: Checking python file
        run: python3 GitDemo1/ci_file_demo.py
